# Generated by Django 4.2.6 on 2023-10-31 16:51

from django.db import (
    migrations,
    models,
)
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PhoneNumber",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(max_length=30),
                ),
            ],
        ),
        migrations.CreateModel(
            name="VerificationPair",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(max_length=10),
                ),
                (
                    "phone_number",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mob_number_checker.phonenumber",
                    ),
                ),
            ],
        ),
    ]
